stages:
 - add_remote
 - push_remote

job add_remote_github:
  stage: add_remote
  script: 
    - git remote add github git@github.com:imhuwq/$CI_PROJECT_NAME.git
  allow_failure: true

job push_github:
 stage: push
 script:
  - git push github
  - git push github --tags
